# Generated by Django 6.0.5 on 2026-08-07 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(help_text='e.g., 9 Days / 8 Nights', max_length=50)),
                ('start_location', models.CharField(default='Yangon', max_length=100)),
                ('end_location', models.CharField(default='Yangon', max_length=100)),
                ('main_image', models.ImageField(upload_to='packages/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='packages/')),
            ],
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_category', models.CharField(max_length=100)),
                ('travelers_count', models.CharField(max_length=50)),
                ('travel_date', models.DateField()),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.travelpackage')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trip.travelpackage')),
            ],
        ),
    ]
