# Generated by Django 6.0.5 on 2026-08-08 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('travel_style', models.CharField(choices=[('Group Tour Packages', 'Group Tour Packages'), ('Honeymoon Packages', 'Honeymoon Packages'), ('Culture & History Packages', 'Culture & History Packages'), ('Luxury & Premium Packages', 'Luxury & Premium Packages'), ('Budget Packages', 'Budget Packages'), ('Adventure & Trekking Packages', 'Adventure & Trekking Packages'), ('Beach & Island Package', 'Beach & Island Package')], default='Group Tour Packages', max_length=100)),
                ('start_location', models.CharField(default='Yangon', max_length=100)),
                ('end_location', models.CharField(default='Yangon', max_length=100)),
                ('base_price_mmk', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration', models.CharField(help_text='e.g. 3 Days / 2 Nights', max_length=50)),
                ('rating', models.FloatField(default=4.7)),
                ('price_2_star', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_3_star', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_4_star', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_5_star', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('main_image', models.ImageField(upload_to='packages/')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('description', models.TextField()),
                ('price_includes', models.TextField()),
                ('price_excludes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_category', models.CharField(max_length=50)),
                ('travelers_count', models.CharField(max_length=50)),
                ('travel_date', models.DateField()),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('payment_method', models.CharField(max_length=100)),
                ('payment_option', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('pay_slip', models.ImageField(upload_to='pay_slips/')),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trip.tourpackage')),
            ],
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='trip.tourpackage'),
        ),
        migrations.DeleteModel(
            name='TourBooking',
        ),
        migrations.DeleteModel(
            name='TravelPackage',
        ),
    ]
