# Generated by Django 6.0.5 on 2026-08-08 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_tourpackage_booking_alter_itinerary_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='hotel_category',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pay_slip',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='payment_option',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travelers_count',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='base_price_mmk',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_2_star',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_3_star',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_4_star',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_5_star',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_excludes',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='price_includes',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tourpackage',
            name='travel_style',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_2star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_3star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_4star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_5star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.tourpackage'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='day_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.CharField(max_length=100),
        ),
    ]
