# Generated by Django 6.0.5 on 2026-08-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_booking_email_booking_full_name_booking_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='price_excludes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_includes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
