# Generated by Django 6.0.5 on 2026-08-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20, null=True),
        ),
    ]
