# Generated by Django 6.0.5 on 2026-08-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='price_2star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price_3star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price_4star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price_5star',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
