# Generated by Django 6.0.5 on 2026-08-09 17:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_review_delete_tourreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='TourReview',
        ),
    ]
