# Generated by Django 6.0.5 on 2026-08-18 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_customtripplan_delete_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='title',
            field=models.TextField(),
        ),
    ]
