# Generated by Django 6.0.5 on 2026-08-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_alter_itinerary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='description_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='title_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='title_my',
            field=models.TextField(blank=True, null=True),
        ),
    ]
