# Generated by Django 6.0.5 on 2026-08-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_itinerary_description_en_itinerary_description_my_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='title_en',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='description_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_excludes_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_includes_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='tagline_my',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='title_my',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
