# Generated by Django 6.0.5 on 2026-08-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0022_remove_itinerary_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='duration_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
