# Generated by Django 6.0.5 on 2026-08-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0023_tourpackage_duration_my'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='end_location_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='start_location_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
