# Generated by Django 6.0.5 on 2026-08-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0024_tourpackage_end_location_my_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelagency',
            name='description_my',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelagency',
            name='name_my',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
