# Generated by Django 6.0.5 on 2026-08-19 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0025_travelagency_description_my_travelagency_name_my'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelagency',
            name='description_my',
        ),
        migrations.RemoveField(
            model_name='travelagency',
            name='name_my',
        ),
    ]
