# Generated by Django 6.0.5 on 2026-08-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0027_travelagency_description_my_travelagency_name_my'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='price_2star_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_3star_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_4star_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='price_5star_my',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
